version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile 

    ports:
      - "3000:3000"
      - "5501:5501"
      - "7071:7071"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

volumes:
  mongodb-data:
